// One frozen experiment drives every view. UI activity never substitutes for simulation.
const stageDefinitions={
 source:['A 外部声源','panel-source','声压 Pa、载频、IPI 和 RMS 控制位于声源层。'],
 ear:['B–C 人耳层','panel-ear','OpenEar 为真实几何；机械响应按演示、直通或导入模式标注。'],
 features:['D 特征提取','panel-encoder','包络和相对幅度使用固定共享标定，测试片段不重新拟合。'],
 encoder:['E–F 编码输入','panel-encoder','编码率转换成冻结的独立通道感觉事件。'],
 network:['G–H 真实结构','panel-network','连接组约束模型边；hop 是原始子图分组。'],
 synapse:['I 突触传递','panel-synapse','模型前突触放电加延迟，形成对目标的带符号 ΔV 排程。'],
 activity:['J–K 响应分析','panel-overview','群体放电、膜电压和真实 SWC 共用同一实验时间轴。']
};
let activeStage=new URLSearchParams(location.search).get('stage')||'source';
if(!stageDefinitions[activeStage])activeStage='source';
let dirty=false,computing=false,dirtyStages=new Set(),syncMorphCache=null,syncIndex=null,rasterBase=null,heatBase=null,journeyPinned=null;
function upperBound(values,value){let lo=0,hi=values.length;while(lo<hi){const mid=(lo+hi)>>>1;if(values[mid]<=value)lo=mid+1;else hi=mid}return lo}
const countWindow=(values,end,width=20)=>upperBound(values,end)-upperBound(values,end-width);
function arrivalBound(value){let lo=0,hi=R.arrivals.length;while(lo<hi){const m=(lo+hi)>>>1;if(R.arrivals[m][0]<=value)lo=m+1;else hi=m}return lo}
function setOperation(stage,message='',scroll=false){if(!stageDefinitions[stage])return;activeStage=stage;const [label,panel,explanation]=stageDefinitions[stage];$('stageTitle').textContent='当前位置：'+label;$('stageContext').textContent=(message?message+' ':'')+explanation;document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.stage===stage)));document.querySelectorAll('.focus-panel').forEach(e=>e.classList.remove('focus-panel'));$(panel).classList.add('focus-panel');if(scroll)$(panel).scrollIntoView({behavior:'smooth',block:'start'});if(window.parent!==window&&location.origin!=='null')window.parent.postMessage({type:'workbench-stage',stage},location.origin)}
function updateExperimentBadge(){if(!R)return;$('overviewExperiment').textContent=(dirty?'参数待运行；':computing?'计算中；':'')+`当前冻结实验：${R.id} · ${R.parameters.kind} / ${R.parameters.frequency_hz} Hz · ${R.parameters.topology} · ${t.toFixed(1)} ms。无声时仍可能有预设背景感觉活动。`;}
function refreshSnapshot(){if(!R)return;updateExperimentBadge();const e=$('snapshotState');e.classList.toggle('pending',dirty||computing);e.textContent=(computing?'正在计算新实验；当前画面仍为已冻结结果。 ':dirty?'参数已修改，待重新仿真；当前画面仍为旧结果。 ':'正在回放冻结结果。 ')+`实验 ${R.id} · ${R.parameters.kind} / ${R.parameters.frequency_hz} Hz · 输入哈希 ${R.input_sha256.slice(0,12)}…`;document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('draft',dirtyStages.has(b.dataset.stage));b.classList.toggle('bypassed',b.dataset.stage==='ear'&&R.parameters.mechanical==='direct');b.querySelector('[data-state]').textContent=computing?'新实验计算中':dirtyStages.has(b.dataset.stage)?'参数待运行':b.dataset.stage==='ear'&&R.parameters.mechanical==='direct'?'本实验直通绕过':'冻结结果已载入'})}
function setDraft(value,stage='source'){dirty=value;if(value){const keys=Object.keys(stageDefinitions),at=keys.indexOf(stage);keys.slice(at).forEach(k=>dirtyStages.add(k))}else dirtyStages.clear();refreshSnapshot()}
function setComputing(value){computing=value;refreshSnapshot()}
function prepareSynchronization(){journeyPinned=null;const byHop=[[],[],[]],groupSizes=[0,0,0];B.nodes.forEach((n,i)=>{byHop[n.hop].push(...R.spikes[i]);groupSizes[n.hop]++});byHop.forEach(a=>a.sort((a,b)=>a-b));const bins=Math.ceil(R.duration_ms/10),rates=byHop.map((spikes,hop)=>Array.from({length:bins},(_,k)=>{const start=k*10,end=Math.min((k+1)*10,R.duration_ms);return (upperBound(spikes,end-1e-7)-upperBound(spikes,start-1e-7))/(Math.max(1,groupSizes[hop])*(end-start)/1000)}));syncIndex={byHop,groupSizes,rates,input:R.input_events.map(e=>e[0]).sort((a,b)=>a-b),arrivalsByEdge:R.edges.map(()=>[]),incoming:B.nodes.map(()=>[]),maxDelay:Math.max(.1,...R.edges.map(e=>e[3]))};R.arrivals.forEach(([at,ei])=>{syncIndex.arrivalsByEdge[ei].push(at);syncIndex.incoming[R.edges[ei][1]].push([at,ei])});rasterBase=null;heatBase=null}
function drawActivityEdges(c,w,h,id){if(!syncIndex)return;const lo=arrivalBound(t-20),hi=arrivalBound(t+syncIndex.maxDelay),recent=R.arrivals.slice(lo,hi).filter(([at,ei])=>at<=t||at-R.edges[ei][3]<=t);let visible=recent.slice(-80);const selectedEvents=recent.filter(a=>a[1]===selectedEdge);visible=visible.filter(a=>a[1]!==selectedEdge).concat(selectedEvents).slice(-100);for(const[at,ei]of visible){const[a,b,dv,delay]=R.edges[ei],p=xy(a,w,h),q=xy(b,w,h),age=t-(at-delay);c.strokeStyle=dv>=0?'#ffcc70':'#72b9ff';c.globalAlpha=at>t?.65:Math.max(.06,1-(t-at)/20)*.35;c.lineWidth=ei===selectedEdge?2:1;c.beginPath();c.moveTo(...p);c.lineTo(...q);c.stroke();if(age>=0&&age<=delay){const fraction=age/delay;c.globalAlpha=.95;c.fillStyle=dv>=0?'#ffda8e':'#72b9ff';c.beginPath();c.arc(p[0]+fraction*(q[0]-p[0]),p[1]+fraction*(q[1]-p[1]),ei===selectedEdge?4:2.5,0,Math.PI*2);c.fill()}}c.globalAlpha=1;if(id==='syncGraph')$('propagationCount').textContent=`20 ms 内到达 ${arrivalBound(t)-lo} 次；当前在途 ${recent.filter(([at])=>at>t).length} 次。为清晰最多画 100 个排程事件，全部连接仍参与仿真。`}
function drawSyncTraces(){const[c,w,h]=setup('syncTraces'),x=R.trace.time_ms,idx=Math.max(0,upperBound(x,t)-1),start=Math.max(0,t-40),end=Math.min(R.duration_ms,t+40),rows=[['声压 Pa',R.trace.pressure_pa,'#38bdf8'],['归一化包络',R.trace.normalized,'#86efac'],['编码率 Hz',R.trace.rate_hz,'#fb923c']];rows.forEach(([label,y,color],row)=>{const y0=17+row*72,lo=Math.min(0,...y),hi=Math.max(1e-9,...y),px=v=>100+(v-start)/Math.max(1,end-start)*(w-115),py=v=>y0+49-(v-lo)/(hi-lo)*42;c.font='11px sans-serif';c.fillStyle=color;c.fillText(label,8,y0+15);c.fillText(y[idx].toPrecision(3),8,y0+33);c.strokeStyle=color;c.beginPath();let begun=false;for(let i=0;i<x.length;i++){if(x[i]<start||x[i]>end)continue;if(!begun){c.moveTo(px(x[i]),py(y[i]));begun=true}else c.lineTo(px(x[i]),py(y[i]))}c.stroke();c.strokeStyle='#f8dc82';c.beginPath();c.moveTo(px(t),y0);c.lineTo(px(t),y0+54);c.stroke();c.fillStyle='#9db1c9';c.fillText(`${start.toFixed(1)} — ${end.toFixed(1)} ms`,100,y0+66)})}
function drawPopulation(){const[c,w,h]=setup('population'),max=Math.max(1,...syncIndex.rates.flat()),height=(h-40)/3;c.font='11px sans-serif';syncIndex.rates.forEach((rates,hop)=>{const base=28+(hop+1)*height;c.fillStyle=COL[hop];c.fillText(['JO 感觉细胞','原 hop 1','原 hop 2'][hop]+` · ${syncIndex.groupSizes[hop]} cells`,8,base-height+3);c.strokeStyle=COL[hop];c.beginPath();rates.forEach((v,k)=>{const x=35+(k+.5)*10/R.duration_ms*(w-50),y=base-9-v/max*(height-22);if(!k)c.moveTo(x,y);else c.lineTo(x,y)});c.stroke()});c.strokeStyle='#f8dc82';c.beginPath();c.moveTo(35+t/R.duration_ms*(w-50),15);c.lineTo(35+t/R.duration_ms*(w-50),h-20);c.stroke();c.fillStyle='#9db1c9';c.fillText(`平均 Hz / 细胞；统一上界 ${max.toFixed(1)} Hz；10 ms 分箱`,10,h-5)}
function journeyEvent(){if(selectedEdge<0)return null;if(journeyPinned?.ei===selectedEdge)return journeyPinned.at;const times=syncIndex.arrivalsByEdge[selectedEdge],atIndex=upperBound(times,t),past=times[atIndex-1],future=times[atIndex];if(past===undefined&&future===undefined)return null;return future!==undefined&&(past===undefined||future-t<t-past)?future:past}
function drawJourney(){const box=$('eventJourney');box.replaceChildren();const at=journeyEvent();if(at===null){box.textContent='选中边没有监测到的前突触放电，无法演示该边的延迟事件。'}else{const[a,b,dv,delay]=R.edges[selectedEdge],pre=at-delay,post=R.spikes[b][upperBound(R.spikes[b],at-1e-7)],following=post!==undefined&&post<=at+8?post:null;const parts=[['前突触放电',`${B.nodes[a].type} · ${pre.toFixed(2)} ms`,Math.abs(t-pre)<=.2],['延迟排程',`${delay.toFixed(2)} ms · ${t<pre?'尚未发放':t<at?'在途':'已到达'}`,t>=pre&&t<at],['目标电压更新',`${at.toFixed(2)} ms · ΔV ${dv.toFixed(3)} mV`,t>=at&&t<at+.2],['目标随后发放',following===null?'到达后 8 ms 内未发放':`${B.nodes[b].type} · ${following.toFixed(2)} ms`,following!==null&&Math.abs(t-following)<=.2]];parts.forEach(([title,text,now])=>{const e=document.createElement('div');e.classList.toggle('now',now);const b=document.createElement('b'),p=document.createElement('p');b.textContent=title;p.textContent=text;e.append(b,p);box.append(e)})}
const incoming=syncIndex.incoming[selected];let positive=0,negative=0,count=0;let lo=0,hi=incoming.length;while(lo<hi){const m=(lo+hi)>>>1;if(incoming[m][0]<=t-20)lo=m+1;else hi=m}for(let i=lo;i<incoming.length&&incoming[i][0]<=t;i++){const dv=R.edges[incoming[i][1]][2];if(dv>=0)positive+=dv;else negative+=dv;count++}const vi=nearestTime();$('cooperationInfo').textContent=`目标 ${B.nodes[selected].id} · ${B.nodes[selected].type}：V(${R.voltage_time_ms[vi].toFixed(1)} ms) = ${R.voltage_mv[selected][vi].toFixed(2)} mV；阈值 −50 mV。\n20 ms 内全部入边 ${count} 次排程到达：正向 ΔV 累计 +${positive.toFixed(3)} mV，负向 ${negative.toFixed(3)} mV。漏电、不应期与复位使它们不能直接等同于净电压变化。`}
function cacheRaster(){rasterBase=$('raster').getContext('2d').getImageData(0,0,$('raster').width,$('raster').height);heatBase=$('heatmap').getContext('2d').getImageData(0,0,$('heatmap').width,$('heatmap').height)}
function drawRasterCursor(){for(const[id,base]of [['raster',rasterBase],['heatmap',heatBase]]){if(!base)continue;const canvas=$(id),c=canvas.getContext('2d'),r=canvas.getBoundingClientRect();c.putImageData(base,0,0);c.strokeStyle='#f8dc82';c.lineWidth=1;c.beginPath();const x=30+t/R.duration_ms*(r.width-(id==='raster'?42:40));c.moveTo(x,18);c.lineTo(x,r.height-22);c.stroke()}}
function updateSynchronized(){if(!syncIndex)return;updateExperimentBadge();const idx=Math.max(0,upperBound(R.trace.time_ms,t)-1);$('syncPressure').textContent=R.trace.pressure_pa[idx].toFixed(3);$('syncRate').textContent=R.trace.rate_hz[idx].toFixed(1);$('syncInput').textContent=countWindow(syncIndex.input,t);['syncJO','syncH1','syncH2'].forEach((id,hop)=>$(id).textContent=countWindow(syncIndex.byHop[hop],t));drawSyncTraces();drawPopulation();drawGraph('syncGraph');drawMorph('syncMorph');drawJourney();drawRasterCursor();const strength={source:Math.min(1,Math.abs(R.trace.pressure_pa[idx])/Math.max(1e-8,R.features.peak_pressure_pa)),ear:R.parameters.mechanical==='direct'?0:R.trace.normalized[idx],features:R.trace.normalized[idx],encoder:R.trace.rate_hz[idx]/150,network:countWindow(syncIndex.byHop[0],t)/Math.max(1,syncIndex.groupSizes[0]),synapse:(arrivalBound(t)-arrivalBound(t-20))/300,activity:countWindow(syncIndex.byHop[1],t)/Math.max(1,syncIndex.groupSizes[1])};document.querySelectorAll('[data-stage]').forEach(b=>{b.querySelector('.stage-level i').style.width=Math.min(100,Math.max(0,strength[b.dataset.stage]*100))+'%';b.title='当前时间 '+t.toFixed(1)+' ms；条形仅用于观察强度，不是计算进度。'+({source:'|声压| / 本实验峰值',ear:R.parameters.mechanical==='direct'?'人耳层绕过':'观察代理：归一化包络 z',features:'归一化包络 z',encoder:'编码率 / 150 Hz',network:'JO 放电数 / 20 ms / JO 细胞数',synapse:'到达次数 / 20 ms / 300',activity:'hop 1 放电数 / 20 ms / 细胞数'}[b.dataset.stage])})}
function chooseGuidedEvent(){if(!R)return;let best=null;for(const[at,ei]of R.arrivals){const[a,b,,delay]=R.edges[ei];if(at-delay<200||at>=R.duration_ms-200||B.nodes[b].hop===0)continue;const after=R.spikes[b][upperBound(R.spikes[b],at-1e-7)];const score=(B.nodes[a].seed?10:0)+(after!==undefined&&after<=at+8?5:0);if(!best||score>best.score)best={at,ei,a,b,delay,score};if(score===15)break}if(!best){status('当前实验未监测到刺激窗口内的下游突触到达，请检查输入或选择其他实验。');return}selectNode(best.b);selectedEdge=best.ei;$('edge').value=String(selectedEdge);edgeDetails();journeyPinned={ei:selectedEdge,at:best.at};t=Math.max(0,best.at-best.delay-.5);$('time').value=t;$('speed').value='0.1';playing=true;last=performance.now();$('play').textContent='暂停';setOperation('synapse','正在慢放实际模型事件；相邻的目标 spike 只表示时间关联。');$('panel-overview').scrollIntoView({behavior:'smooth',block:'start'});update()}
function graphSelection(e){if(!R)return;const r=e.currentTarget.getBoundingClientRect(),point=[e.clientX-r.left,e.clientY-r.top];let nearest=0,distance=Infinity;B.nodes.forEach((n,i)=>{const p=xy(i,r.width,r.height),d=(point[0]-p[0])**2+(point[1]-p[1])**2;if(d<distance){distance=d;nearest=i}});selectNode(nearest);setOperation('network','已选中细胞；两处拓扑、SWC、膜电压和入边事件同步切换。')}
$('syncGraph').onclick=graphSelection;$('graph').addEventListener('click',()=>setOperation('network','已选中细胞及其入边。'));
$('overviewStart').onclick=()=>{t=Math.max(0,(R.config.fixed_input.onset_s??.2)*1000-20);$('time').value=t;$('speed').value='5';playing=true;last=performance.now();$('play').textContent='暂停';setOperation('activity','从刺激前 20 ms 开始联动回放。');$('panel-overview').scrollIntoView({behavior:'smooth',block:'start'});update()};
$('guidedEvent').onclick=chooseGuidedEvent;
for(const b of document.querySelectorAll('[data-stage]'))b.onclick=()=>setOperation(b.dataset.stage,'已定位对应操作面板。',true);
const operationFields={kind:'source',frequency_hz:'source',amplitude_pa:'source',ipi_ms:'source',modulation_hz:'source',rmsEnabled:'source',rmsTarget:'source',wav:'source',mechanical:'ear',femFile:'ear',calibrationFile:'ear',encoder_gain:'encoder',seed:'encoder',topology:'network',w0_mv:'synapse',input_weight_mv:'synapse',delay_ms:'synapse',tau_m_ms:'synapse'};
for(const[id,stage]of Object.entries(operationFields))for(const event of ['input','change'])$(id).addEventListener(event,()=>{setDraft(true,stage);setOperation(stage,'参数修改尚未进入冻结结果；点击重新仿真后观察响应。')});
for(const[id,stage]of [['node','network'],['edge','synapse'],['mechanicalTrace','ear'],['scope','activity'],['time','activity'],['display','activity']])$(id).addEventListener('change',()=>{setOperation(stage,'仅改变观察位置或展示方式；未改变模型数据。');update()});
$('next').addEventListener('click',()=>setOperation('synapse','已定位选中边的实际模型事件。'));
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===window.parent&&e.data?.type==='research-stage'&&stageDefinitions[e.data.stage])setOperation(e.data.stage,'科研报告选择的链路环节。',true)});
setOperation(activeStage);

for(const id of ['edge','node','time'])$(id).addEventListener('input',()=>{journeyPinned=null});

$('time').addEventListener('input',()=>setOperation('activity','拖动时间轴，全部活动视图同步更新。'));

$('syncMorph').onwheel=$('morph').onwheel;

$('time').addEventListener('input',()=>{playing=false;$('play').textContent='播放'});
