// End-to-end check over the real local assets. Run with an isolated Edge CDP port.
const fs=require('node:fs'),{pathToFileURL}=require('node:url'),path=require('node:path');
const debugPort=Number(process.env.SYNC_DEBUG_PORT||9227),base=process.env.SYNC_APP_URL||'http://127.0.0.1:8765';
(async()=>{
 let pages;for(let attempt=0;attempt<100;attempt++){try{pages=await(await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json();if(pages.some(p=>p.type==='page'))break}catch{}await new Promise(r=>setTimeout(r,100))}const page=pages?.find(p=>p.type==='page');if(!page)throw Error('No test browser page');
 const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let sequence=0;const pending=new Map(),errors=[],tests=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.j(m.error):p.r(m.result)}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails)};
 const call=(method,params={})=>new Promise((r,j)=>{const id=++sequence;pending.set(id,{r,j});ws.send(JSON.stringify({id,method,params}))});
 const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=expression=>ev(`new Promise((resolve,reject)=>{let n=0;const timer=setInterval(()=>{if(${expression}){clearInterval(timer);resolve(true)}else if(++n>600){clearInterval(timer);reject(Error('Timed out: readiness'))}},100)})`);
 const check=(name,ok,detail)=>{tests.push({name,pass:!!ok,detail});if(!ok)throw Error(name+': '+JSON.stringify(detail))};
 const child=expression=>ev(`document.getElementById('linkedWorkbench').contentWindow.eval(${JSON.stringify(expression)})`);
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1350,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:base+'/research'});await wait('window.RESEARCH_READY');
 let v=await ev(`({trials:D.trials.length,stage:reportStage,embedded:!frame.getAttribute('src')})`);check('frozen statistics preserved and workbench lazy loaded',v.trials===65&&v.stage==='statistics'&&v.embedded,v);
 await ev(`document.querySelector('[data-stage="encoder"]').click()`);await wait(`document.getElementById('linkedWorkbench').contentWindow.WORKBENCH_READY`);
 v=await child(`({stage:activeStage,focus:$('panel-encoder').classList.contains('focus-panel'),nodes:B.nodes.length,voltage:R.voltage_mv.length,input:$('syncInput').textContent})`);check('report chain opens matching real workbench section',v.stage==='encoder'&&v.focus&&v.nodes===265&&v.voltage===265,v);
 await child(`$('amplitude_pa').value=.8;$('amplitude_pa').dispatchEvent(new Event('input'));`);await wait(`reportStage==='source'`);v=await child(`({dirty,stage:activeStage,frozen:R.parameters.amplitude_pa,message:$('snapshotState').textContent,marked:document.querySelector('[data-stage="source"]').classList.contains('draft')})`);check('draft parameters do not masquerade as simulation',v.dirty&&v.stage==='source'&&v.frozen===1&&v.marked&&v.message.includes('旧结果'),v);
 v=await child(`(async()=>{const old=R.id;$('kind').value='pulse';$('ipi_ms').value=36;$('rmsEnabled').checked=true;$('rmsTarget').value=.5;await runExperiment();return {different:old!==R.id,dirty,rms:R.features.stimulus_rms_pa,input:R.input_events.length,spikes:R.network_spikes,kind:R.parameters.kind}})()`);check('new source stimulus runs actual Brian2 and refreshes all views',v.different&&!v.dirty&&Math.abs(v.rms-.5)<1e-8&&v.kind==='pulse'&&v.spikes>0,v);
 v=await child(`t=275.5;$('time').value=t;$('time').dispatchEvent(new Event('input'));({time:t,input:Number($('syncInput').textContent),expected:R.input_events.filter(e=>e[0]>t-20&&e[0]<=t).length,hop1:Number($('syncH1').textContent),expectedHop1:R.spikes.flatMap((s,i)=>B.nodes[i].hop===1?s:[]).filter(x=>x>t-20&&x<=t).length,clock:$('clock').textContent})`);check('shared cursor and window counts agree with frozen events',v.input===v.expected&&v.hop1===v.expectedHop1&&v.clock==='275.5 ms',v);
 v=await child(`chooseGuidedEvent();playing=false;$('play').textContent='播放';const e=R.edges[selectedEdge],at=journeyPinned.at;t=at-e[3]/2;update();({pinned:journeyEvent()===at,inFlight:$('eventJourney').children[1].classList.contains('now'),post:$('eventJourney').children[3].textContent,actual:R.spikes[e[1]].filter(x=>x>=at&&x<=at+8).length,edge:selectedEdge,afterOnset:at-e[3]>=200,exact:R.arrivals.some(a=>a[0]===at&&a[1]===selectedEdge)})`);check('event guide uses monitored spikes and true modeled delay',v.pinned&&v.inFlight&&v.exact&&v.actual>0&&v.afterOnset,v);
 v=await child(`(async()=>{const node=selected,incoming=R.arrivals.filter(a=>R.edges[a[1]][1]===node&&a[0]>t-20&&a[0]<=t),cache=morphCache,overviewCache=syncMorphCache;update();const reused=cache===morphCache&&overviewCache===syncMorphCache;const start=performance.now();for(let k=0;k<5;k++)update();return {reused,meanUpdateMs:(performance.now()-start)/5,incoming:incoming.length,text:$('cooperationInfo').textContent}})()`);check('all incoming events explained and both projection caches reused',v.reused&&v.text.includes(`${v.incoming} 次排程到达`),v);
 v=await child(`(async()=>{t=300;$('speed').value='5';playing=true;last=performance.now();await new Promise(r=>setTimeout(r,250));playing=false;return {time:t,moved:t>300&&t<330}})()`);check('elapsed-time playback advances synchronized activity',v.moved,v);
 await ev(`document.querySelector('[data-stage="synapse"]').click()`);v=await child(`({stage:activeStage,focus:$('panel-synapse').classList.contains('focus-panel')})`);check('report and workbench navigation remains bidirectional',v.stage==='synapse'&&v.focus,v);
 v=await ev(`$('group').value='rms';$('group').dispatchEvent(new Event('change'));({stage:reportStage,trials:D.trials.length,rows:$('stats').children.length})`);check('statistics selection locates statistical stage without modifying batch',v.stage==='statistics'&&v.trials===65&&v.rows===3,v);
 const exported=await child(`fetch('/api/export/'+R.id).then(r=>r.text())`);fs.mkdirSync('outputs/workbench',{recursive:true});fs.writeFileSync('outputs/workbench/sync_offline.html',exported);
 await call('Page.navigate',{url:pathToFileURL(path.resolve('outputs/workbench/sync_offline.html')).href});await wait('window.WORKBENCH_READY');v=await ev(`t=315;update();({offline:!!window.WORKBENCH_OFFLINE,disabled:$('run').disabled&&$('case').disabled,pressure:$('syncPressure').textContent,clock:$('clock').textContent,hasEvents:syncIndex.byHop[0].length>0})`);check('self-contained offline report supports synchronized replay',v.offline&&v.disabled&&v.clock==='315.0 ms'&&v.hasEvents,v);

 await call('Emulation.setDeviceMetricsOverride',{width:720,height:1050,deviceScaleFactor:1,mobile:false});v=await ev(`update();({width:document.documentElement.scrollWidth,viewport:innerWidth,columns:getComputedStyle(document.querySelector('.sync-view')).gridTemplateColumns,toolbar:getComputedStyle(document.querySelector('.toolbar')).position})`);check('narrow viewport remains operable without page overflow',v.width<=v.viewport+1&&v.toolbar==='static',v);
 const reportHTML=await(await fetch(base+'/research')).text();fs.writeFileSync('outputs/research/interactive-current.html',reportHTML);await call('Page.navigate',{url:pathToFileURL(path.resolve('outputs/research/interactive-current.html')).href});await wait('window.RESEARCH_READY');v=await ev(`document.querySelector('[data-stage="source"]').click();({notice:!$('offlineNotice').hidden,disabled:$('openLinked').disabled,unloaded:!frame.getAttribute('src'),stage:reportStage,trials:D.trials.length})`);check('offline research retains statistics and explicit live-operation boundary',v.notice&&v.disabled&&v.unloaded&&v.stage==='source'&&v.trials===65,v);
 await call('Emulation.setDeviceMetricsOverride',{width:1600,height:1350,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base+'/?stage=activity'});await wait('window.WORKBENCH_READY');await ev(`t=280;$('time').value=t;update();$('panel-overview').scrollIntoView({block:'start'})`);const image=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync('outputs/workbench/sync_overview_preview.png',Buffer.from(image.data,'base64'));
 check('no uncaught browser application errors',errors.filter(e=>!(e.url||'').startsWith('chrome-extension://')).length===0,errors);
 fs.writeFileSync('outputs/workbench/sync_browser_qa.json',JSON.stringify({tests},null,2));console.log(JSON.stringify({tests},null,2));ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
